sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-publishers latex-xcolor
script:
- pdflatex -interaction=nonstopmode -halt-on-error Alexander_McGinn.tex

deploy:
  provider: releases
  file:
  - Alexander_McGinn.pdf
  skip_cleanup: true
  overwrite: true
